---
ingress:
  enabled: true
  tls:
    enabled: true
    certSource: auto
  hosts: prod.notejam.domain
  annotations: {}

databases:
  sqlite:
    enabled: false
    path: /data/
  mysql:
    enabled: true
    host: prod-db.notejam.domain

image:
  repository: ghcr.io/flaviodsr/notejam
  tag: v0.1
