---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: notejam-app
  labels:
    app.kubernetes.io/name: notejam
spec:
  scaleTargetRef:
    kind: Deployment
    name: notejam-app
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
